---
north_interfaces:
  - swp31
  - swp32
bridge_interfaces:
- swp1
- swp2
- swp3
- swp4
- swp5
- swp6
- swp7
- swp8
- swp9
- swp10
- swp11
- swp12
- swp13
- swp14
- swp15
- swp16
- swp17
- swp18
- swp19
- swp20
- swp21
- swp22
- swp23
- swp24
- swp25
- swp26
- swp27
- swp28
- swp29
- swp30
